### ISSUE TITLE
Ascii art not readable on mobile app

### ISSUE THREAD

**Issue by emilevauge** [containous/flaeg#22]
The flaeg ascii art logo is not readable on mobile device:
![screenshot_20160525-130215](https://cloud.githubusercontent.com/assets/6207234/15537915/4587394e-2279-11e6-8af7-b1a0857c2f6f.png)

**Comment by cocap10** [comment]
I'll upload a screenshot ;)

**Comment by emilevauge** [comment]
To make it simpler, for now, could you just write a simple title? Like in https://github.com/containous/staert ? We will think about logos later ;)

**Comment by cocap10** [comment]
Ok
