### ISSUE TITLE
Pull parser.go into a separate package

### ISSUE THREAD

**Issue by serbrech** [containous/flaeg#40]
To implement https://github.com/containous/staert/issues/35 and reuse the parsing code, it will be good to reuse flaeg parser, as suggested for a previous tentative : https://traefik.slackarchive.io/dev/page-17/ts-1497598028679523

This requires quite a lot of renaming and prefixing in the code, so I'd like to make sure I plan this right

- Suggested package name : `parse`
- Keep it under flaeg, not a different repo
- Move `parser.go` and `parser_test.go` into a `parse` folder. rename files to `parse.go/parse_test.go`
- Import `github.com/containous/flaeg/parse` in `flaeg` 
- Make all types in parse public
- Prefix every call to parse types by `parse.`
- Same in test files
- There is a lot of repetition in the flaeg tests, maybe look into refactoring 

Sounds good?

**Comment by ldez** [comment]
We agree with your plan.
Please don't do non-needed refactoring, split your PR**s** in well formed commits (and good commit message too) and try to do several PRs to facilitate the reviews.
Thanks, good luck 😉
